subscription PotRecordsById($id: String!) {
  getPotRecordsIRT(id: $id) {
    potId
    potName
    total
    measurements {
      ph {
        min
        max
        values {
          timestamp
          value
        }
      }
      humidity {
        min
        max
        values {
          timestamp
          value
        }
      }
      temperature {
        min
        max
        values {
          timestamp
          value
        }
      }
    }
  }
}